<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ApplicantAdmission.DataAccess\ApplicantAdmission.DataAccess.csproj" />
    <ProjectReference Include="..\ApplicantAdmission.Infrastructure\ApplicantAdmission.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
