// <auto-generated />
using System;
using ApplicantAdmission.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApplicantAdmission.DataAccess.Migrations
{
    [DbContext(typeof(ApplicantDbContext))]
    [Migration("20251130094944_SeedDataAndFixes")]
    partial class SeedDataAndFixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.AdmissionProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("AdmissionPrograms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProgramId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.ApplicantAdmissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdmissionProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionProgramId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ManagerId");

                    b.ToTable("ApplicantAdmissions");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("FileId");

                    b.ToTable("Documents", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NextLevelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("NextLevelId");

                    b.ToTable("EducationDocumentTypes");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Bachelor"
                        });
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Engineering"
                        });
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FileEntity");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Email = "manager@test.com",
                            FullName = "Admin Manager",
                            PasswordHash = "hashed_pass",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.ProgramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("LevelId");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            FacultyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LevelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Computer Science"
                        });
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocument", b =>
                {
                    b.HasBaseType("ApplicantAdmission.DataAccess.Entities.Document");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("integer");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("EducationDocuments", (string)null);
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.PassportDocument", b =>
                {
                    b.HasBaseType("ApplicantAdmission.DataAccess.Entities.Document");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("PassportDocuments", (string)null);
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.AdmissionProgram", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.ProgramEntity", "Program")
                        .WithMany("AdmissionPrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.ApplicantAdmissionEntity", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.AdmissionProgram", "AdmissionProgram")
                        .WithMany("ApplicantAdmissions")
                        .HasForeignKey("AdmissionProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Applicant", "Applicant")
                        .WithMany("Admissions")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Manager", "Manager")
                        .WithMany("ApplicantAdmissions")
                        .HasForeignKey("ManagerId");

                    b.Navigation("AdmissionProgram");

                    b.Navigation("Applicant");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Document", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Applicant", "Applicant")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.FileEntity", "File")
                        .WithMany("Documents")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("File");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocumentType", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.EducationLevel", "Level")
                        .WithMany("DocumentTypes")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.EducationLevel", "NextLevel")
                        .WithMany()
                        .HasForeignKey("NextLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Level");

                    b.Navigation("NextLevel");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.ProgramEntity", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Faculty", "Faculty")
                        .WithMany("Programs")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.EducationLevel", "Level")
                        .WithMany("Programs")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocument", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.EducationDocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Document", null)
                        .WithOne()
                        .HasForeignKey("ApplicantAdmission.DataAccess.Entities.EducationDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.PassportDocument", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Document", null)
                        .WithOne()
                        .HasForeignKey("ApplicantAdmission.DataAccess.Entities.PassportDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.AdmissionProgram", b =>
                {
                    b.Navigation("ApplicantAdmissions");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Applicant", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationLevel", b =>
                {
                    b.Navigation("DocumentTypes");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Faculty", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.FileEntity", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Manager", b =>
                {
                    b.Navigation("ApplicantAdmissions");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.ProgramEntity", b =>
                {
                    b.Navigation("AdmissionPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
