// <auto-generated />
using System;
using ApplicantAdmission.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApplicantAdmission.DataAccess.Migrations
{
    [DbContext(typeof(ApplicantDbContext))]
    [Migration("20260120192337_FixApplicantAuthSeparation")]
    partial class FixApplicantAuthSeparation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.AdmissionProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("AdmissionPrograms");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Citizenship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Applicants", (string)null);
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.ApplicantAdmissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdmissionProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ManagerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionProgramId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ManagerUserId");

                    b.ToTable("ApplicantAdmissions");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("FileId");

                    b.ToTable("Documents", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("EducationDocumentTypes");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocumentTypeNextLevel", b =>
                {
                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("NextLevelId")
                        .HasColumnType("integer");

                    b.HasKey("DocumentTypeId", "NextLevelId");

                    b.HasIndex("NextLevelId");

                    b.ToTable("EducationDocumentTypeNextLevels");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FileEntity");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.ProgramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("LevelId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Email = "admin@test.local",
                            FullName = "Seeded Admin",
                            IsActive = true,
                            PasswordHash = "AAAAAAAAAAAAAAAAAAAAAA==.EnhHDOCZohHrqGP85zO7Zipwzs4q0OhgUwZQysGSz78=",
                            Phone = "",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            Email = "mgr1@test.local",
                            FullName = "Seeded Manager 1",
                            IsActive = true,
                            PasswordHash = "AQEBAQEBAQEBAQEBAQEBAQ==.T2OFoGXsyB+4m6EU8Cqe+ZayYvxhQGGdxiuZvxXDUYY=",
                            Phone = "",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            Email = "head1@test.local",
                            FullName = "Seeded Head 1",
                            IsActive = true,
                            PasswordHash = "AgICAgICAgICAgICAgICAg==.J+1k/wkwqW+NmBShThK3HzP0VTbZ9il8VemNnUxuy94=",
                            Phone = "",
                            Role = 1
                        });
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocument", b =>
                {
                    b.HasBaseType("ApplicantAdmission.DataAccess.Entities.Document");

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("GraduationYear")
                        .HasColumnType("integer");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("EducationDocuments", (string)null);
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.PassportDocument", b =>
                {
                    b.HasBaseType("ApplicantAdmission.DataAccess.Entities.Document");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("PassportDocuments", (string)null);
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.AdmissionProgram", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.ProgramEntity", "Program")
                        .WithMany("AdmissionPrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Applicant", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.ApplicantAdmissionEntity", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.AdmissionProgram", "AdmissionProgram")
                        .WithMany("ApplicantAdmissions")
                        .HasForeignKey("AdmissionProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Applicant", "Applicant")
                        .WithMany("Admissions")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.UserEntity", "ManagerUser")
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdmissionProgram");

                    b.Navigation("Applicant");

                    b.Navigation("ManagerUser");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Document", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Applicant", "Applicant")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.FileEntity", "File")
                        .WithMany("Documents")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("File");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocumentType", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.EducationLevel", "Level")
                        .WithMany("DocumentTypes")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocumentTypeNextLevel", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.EducationDocumentType", "DocumentType")
                        .WithMany("NextLevels")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.EducationLevel", "NextLevel")
                        .WithMany()
                        .HasForeignKey("NextLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("NextLevel");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.ProgramEntity", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Faculty", "Faculty")
                        .WithMany("Programs")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.EducationLevel", "Level")
                        .WithMany("Programs")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocument", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.EducationDocumentType", null)
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Document", null)
                        .WithOne()
                        .HasForeignKey("ApplicantAdmission.DataAccess.Entities.EducationDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.PassportDocument", b =>
                {
                    b.HasOne("ApplicantAdmission.DataAccess.Entities.Document", null)
                        .WithOne()
                        .HasForeignKey("ApplicantAdmission.DataAccess.Entities.PassportDocument", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.AdmissionProgram", b =>
                {
                    b.Navigation("ApplicantAdmissions");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Applicant", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationDocumentType", b =>
                {
                    b.Navigation("NextLevels");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.EducationLevel", b =>
                {
                    b.Navigation("DocumentTypes");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.Faculty", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.FileEntity", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ApplicantAdmission.DataAccess.Entities.ProgramEntity", b =>
                {
                    b.Navigation("AdmissionPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
